spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aidev
    username: aidev
    password: aidev

  jpa:
    hibernate:
      ddl-auto: update

groq:
  api-key: ${GROQ_API_KEY}

logging:
  level:
    com.max.ai_dev_companion: DEBUG
    root: INFO